/**
 * @file GcodeAnalysis.test.ts
 * @brief Comprehensive tests for the GcodeAnalysis module.
 */

import { describe, it, expect } from 'vitest';
import {
  detectSlicer,
  parseFeatureTypes,
  getFeatureTypeAtLine,
  detectStringingRisk,
  computeVolumetricFlow,
  getFlowStats,
  detectLayerTimeWarnings,
  detectGcodeErrors,
  parseWorkCoordinateSystems,
  getActiveWCS,
  parseStockDimensions,
  estimatePrintTime,
  computeSelectionMetrics,
} from '../src/core/GcodeAnalysis';

// ── Test helpers ──

const CURA_GCODE = [
  ';Generated with Cura 5.0',
  ';TIME:3600',
  'G28 ; home',
  'G1 X10 Y10 Z0.2 F1500',
  'G1 X100 Y10 E5 F1800',
  ';TYPE:WALL-OUTER',
  'G1 X100 Y100 E10 F1800',
  'G1 X10 Y100 E15 F1800',
  ';TYPE:FILL',
  'G1 X50 Y50 E20 F2400',
];

const PRUSA_GCODE = [
  '; generated by PrusaSlicer 2.5.0',
  '; estimated printing time = 1h 30m 0s',
  'G28',
  'M104 S200',
  'M109 S200',
  'G1 X10 Y10 Z0.2 F1500',
  ';TYPE:Perimeter',
  'G1 X100 Y10 E5 F1800',
  ';TYPE:Infill',
  'G1 X100 Y100 E10 F2400',
];

const CNC_GCODE = [
  '%',
  'G54',
  'G0 X0 Y0 Z5',
  'M3 S12000',
  'G1 X10 Y10 Z-1 F500',
  'G2 X20 Y10 R5 F500',
  'M7',
  'G1 X30 Y10 Z-1 F500',
  'M9',
  'M5',
  'G55 X1 Y1',
  'G1 X40 Y10 F500',
  '%',
];

// ── Slicer detection ──

describe('detectSlicer', () => {
  it('detects Cura', () => {
    expect(detectSlicer(CURA_GCODE)).toBe('cura');
  });

  it('detects PrusaSlicer', () => {
    expect(detectSlicer(PRUSA_GCODE)).toBe('prusa');
  });

  it('returns unknown for generic G-code', () => {
    expect(detectSlicer(['G1 X10 Y10 F1000'])).toBe('unknown');
  });

  it('handles empty input', () => {
    expect(detectSlicer([])).toBe('unknown');
  });
});

// ── Feature type parsing ──

describe('parseFeatureTypes', () => {
  it('parses Cura TYPE comments', () => {
    const segments = parseFeatureTypes(CURA_GCODE);
    expect(segments.length).toBe(2);
    expect(segments[0].featureType).toBe('WALL-OUTER');
    expect(segments[0].slicer).toBe('cura');
    expect(segments[1].featureType).toBe('FILL');
  });

  it('parses PrusaSlicer TYPE comments', () => {
    const segments = parseFeatureTypes(PRUSA_GCODE);
    expect(segments.length).toBe(2);
    expect(segments[0].featureType).toBe('PERIMETER');
    expect(segments[0].slicer).toBe('prusa');
    expect(segments[1].featureType).toBe('INFILL');
  });

  it('parses Cura MESH comments', () => {
    const lines = [';MESH:NONMESH', 'G1 X10', ';MESH:Cube'];
    const segments = parseFeatureTypes(lines);
    expect(segments.length).toBe(2);
    expect(segments[0].featureType).toBe('MESH:NONMESH');
    expect(segments[1].featureType).toBe('MESH:CUBE');
  });

  it('parses Cura FEATURE comments', () => {
    const lines = [';FEATURE:Infill', 'G1 X10', ';FEATURE:Wall'];
    const segments = parseFeatureTypes(lines);
    expect(segments.length).toBe(2);
    expect(segments[0].featureType).toBe('INFILL');
    expect(segments[1].featureType).toBe('WALL');
  });

  it('returns empty for no feature comments', () => {
    expect(parseFeatureTypes(['G1 X10 Y10', 'G1 X20 Y20'])).toEqual([]);
  });
});

describe('getFeatureTypeAtLine', () => {
  it('returns the active feature type at a given line', () => {
    const segments = parseFeatureTypes(CURA_GCODE);
    expect(getFeatureTypeAtLine(segments, 0)).toBeNull();
    expect(getFeatureTypeAtLine(segments, 5)).toBe('WALL-OUTER');
    expect(getFeatureTypeAtLine(segments, 8)).toBe('FILL');
  });

  it('returns null for empty segments', () => {
    expect(getFeatureTypeAtLine([], 10)).toBeNull();
  });
});

// ── Stringing risk detection ──

describe('detectStringingRisk', () => {
  it('detects long travel moves', () => {
    const lines = [
      'G1 X0 Y0 E0 F1500',
      'G0 X100 Y0',  // 100mm travel
      'G1 X100 Y10 E5 F1800',
    ];
    const risks = detectStringingRisk(lines, 20);
    expect(risks.length).toBe(1);
    expect(risks[0].travelDistance).toBeCloseTo(100, 1);
    expect(risks[0].riskScore).toBeGreaterThan(0.5);
  });

  it('ignores short travels', () => {
    const lines = [
      'G1 X0 Y0 E0 F1500',
      'G0 X5 Y0',  // 5mm travel — below threshold
      'G1 X5 Y10 E5 F1800',
    ];
    const risks = detectStringingRisk(lines, 20);
    expect(risks.length).toBe(0);
  });

  it('reduces risk score with retraction', () => {
    const lines = [
      'G1 X0 Y0 E10 F1500',
      'G1 X0 Y0 E5 F1800',  // retraction (E decreases)
      'G0 X100 Y0',          // travel with retraction
      'G1 X100 Y10 E10 F1800', // de-retract
    ];
    const risks = detectStringingRisk(lines, 20, true);
    expect(risks.length).toBe(1);
    expect(risks[0].riskScore).toBeLessThan(0.5); // reduced by retraction
  });

  it('reduces risk for pure Z moves', () => {
    const lines = [
      'G1 X50 Y50 E10 F1500',
      'G0 X50 Y50 Z50',  // pure Z move
      'G1 X50 Y50 Z0.2 E15 F1800',
    ];
    const risks = detectStringingRisk(lines, 20);
    expect(risks.length).toBe(1);
    expect(risks[0].riskScore).toBeLessThan(0.2);
  });

  it('handles empty input', () => {
    expect(detectStringingRisk([])).toEqual([]);
  });

  it('handles comments-only lines', () => {
    const lines = ['; comment 1', '; comment 2'];
    expect(detectStringingRisk(lines)).toEqual([]);
  });
});

// ── Volumetric flow rate ──

describe('computeVolumetricFlow', () => {
  it('computes flow rate for extruding moves', () => {
    const lines = [
      'G1 X0 Y0 E0 F1800',  // 1800 mm/min = 30 mm/s
      'G1 X10 Y0 E5 F1800', // extruding move
    ];
    const samples = computeVolumetricFlow(lines, 0.4, 0.2);
    expect(samples.length).toBeGreaterThan(0);
    // Flow = 0.4 * 0.2 * 30 = 2.4 mm³/s
    expect(samples[0].flowRate).toBeCloseTo(2.4, 1);
  });

  it('skips non-extruding moves', () => {
    const lines = [
      'G1 X0 Y0 E0 F1800',
      'G0 X10 Y0',          // rapid move, no E
      'G1 X10 Y10 F1800',   // G1 without E
    ];
    const samples = computeVolumetricFlow(lines);
    expect(samples.length).toBe(0);
  });

  it('skips retractions (negative E delta)', () => {
    const lines = [
      'G1 X0 Y0 E10 F1800',
      'G1 X0 Y0 E5 F1800',  // retraction (E decreases)
      'G1 X10 Y0 E4 F1800', // still negative delta from 5 to 4 — skip
    ];
    const samples = computeVolumetricFlow(lines);
    // Only the first move (E: 0→10) is extruding; the rest are retractions
    expect(samples.length).toBe(1);
  });

  it('parses layer height from comments', () => {
    const lines = [
      ';LAYER_HEIGHT:0.3',
      'G1 X0 Y0 E0 F1200',
      'G1 X10 Y0 E3 F1200',
    ];
    const samples = computeVolumetricFlow(lines, 0.4, 0.2);
    expect(samples.length).toBeGreaterThan(0);
    expect(samples[0].layerHeight).toBeCloseTo(0.3, 2);
  });

  it('parses extrusion width from comments', () => {
    const lines = [
      ';EXTRUSION_WIDTH:0.6',
      'G1 X0 Y0 E0 F1200',
      'G1 X10 Y0 E3 F1200',
    ];
    const samples = computeVolumetricFlow(lines, 0.4, 0.2);
    expect(samples.length).toBeGreaterThan(0);
    expect(samples[0].extrusionWidth).toBeCloseTo(0.6, 2);
  });

  it('estimates layer height from Z changes', () => {
    const lines = [
      'G1 X0 Y0 Z0.2 E0 F1200',
      'G1 X10 Y0 E3 F1200',
      'G1 X0 Y0 Z0.4 E3 F1200',
      'G1 X10 Y0 E6 F1200',
    ];
    const samples = computeVolumetricFlow(lines, 0.4, 0.2);
    expect(samples.length).toBeGreaterThan(0);
    // After Z change from 0.2 to 0.4, layer height should be ~0.2
    const lastSample = samples[samples.length - 1];
    expect(lastSample.layerHeight).toBeCloseTo(0.2, 2);
  });

  it('handles empty input', () => {
    expect(computeVolumetricFlow([])).toEqual([]);
  });
});

describe('getFlowStats', () => {
  it('computes statistics for flow samples', () => {
    const samples = [
      { lineNumber: 0, flowRate: 1.0, feedRate: 10, extrusionWidth: 0.4, layerHeight: 0.2 },
      { lineNumber: 1, flowRate: 2.0, feedRate: 20, extrusionWidth: 0.4, layerHeight: 0.2 },
      { lineNumber: 2, flowRate: 3.0, feedRate: 30, extrusionWidth: 0.4, layerHeight: 0.2 },
    ];
    const stats = getFlowStats(samples);
    expect(stats.minFlow).toBe(1.0);
    expect(stats.maxFlow).toBe(3.0);
    expect(stats.meanFlow).toBeCloseTo(2.0, 2);
    expect(stats.peakLine).toBe(2);
  });

  it('computes standard deviation', () => {
    const samples = [
      { lineNumber: 0, flowRate: 2.0, feedRate: 10, extrusionWidth: 0.4, layerHeight: 0.2 },
      { lineNumber: 1, flowRate: 4.0, feedRate: 20, extrusionWidth: 0.4, layerHeight: 0.2 },
    ];
    const stats = getFlowStats(samples);
    expect(stats.stdDev).toBeCloseTo(1.0, 2);
  });

  it('returns zeros for empty input', () => {
    const stats = getFlowStats([]);
    expect(stats.minFlow).toBe(0);
    expect(stats.maxFlow).toBe(0);
    expect(stats.peakLine).toBe(-1);
  });
});

// ── Layer time warnings ──

describe('detectLayerTimeWarnings', () => {
  it('detects slow layers', () => {
    const layerTimes = [
      { layerIndex: 0, zHeight: 0.2, timeSeconds: 30 },
      { layerIndex: 1, zHeight: 0.4, timeSeconds: 30 },
      { layerIndex: 2, zHeight: 0.6, timeSeconds: 30 },
      { layerIndex: 3, zHeight: 0.8, timeSeconds: 120 }, // 4x average
    ];
    const warnings = detectLayerTimeWarnings(layerTimes, 2.0, 10);
    const slow = warnings.filter(w => w.warning === 'slow');
    expect(slow.length).toBe(1);
    expect(slow[0].layerIndex).toBe(3);
  });

  it('detects fast layers', () => {
    const layerTimes = [
      { layerIndex: 0, zHeight: 0.2, timeSeconds: 30 },
      { layerIndex: 1, zHeight: 0.4, timeSeconds: 5 }, // too fast
    ];
    const warnings = detectLayerTimeWarnings(layerTimes, 2.0, 10);
    const fast = warnings.filter(w => w.warning === 'fast');
    expect(fast.length).toBe(1);
    expect(fast[0].layerIndex).toBe(1);
  });

  it('skips first layer', () => {
    const layerTimes = [
      { layerIndex: 0, zHeight: 0.2, timeSeconds: 600 }, // very slow but first layer
    ];
    const warnings = detectLayerTimeWarnings(layerTimes, 2.0, 10);
    expect(warnings.length).toBe(0);
  });

  it('handles empty input', () => {
    expect(detectLayerTimeWarnings([])).toEqual([]);
  });
});

// ── G-code error detection ──

describe('detectGcodeErrors', () => {
  it('warns about moves before homing', () => {
    const lines = [
      'G1 X10 Y10 F1500', // move before G28
      'G28',
    ];
    const issues = detectGcodeErrors(lines);
    const homing = issues.filter(i => i.category === 'homing');
    expect(homing.length).toBe(1);
    expect(homing[0].severity).toBe('warning');
  });

  it('warns about G1 without feed rate', () => {
    const lines = [
      'G28',
      'G1 X10 Y10', // no F word
    ];
    const issues = detectGcodeErrors(lines);
    const feedrate = issues.filter(i => i.category === 'feedrate');
    expect(feedrate.length).toBeGreaterThanOrEqual(1);
  });

  it('warns about rapid moves with extrusion', () => {
    const lines = [
      'G28',
      'G1 X0 Y0 E0 F1500',
      'G1 X10 Y10 E5 F1500',
      'G0 X20 Y10 E10', // G0 with E increasing (extrusion during rapid)
    ];
    const issues = detectGcodeErrors(lines);
    const rapid = issues.filter(i => i.category === 'rapid-extrusion');
    expect(rapid.length).toBe(1);
  });

  it('warns about extrusion before temperature', () => {
    const lines = [
      'G28',
      'G1 X10 Y10 E5 F1500', // extruding without temp
    ];
    const issues = detectGcodeErrors(lines);
    const temp = issues.filter(i => i.category === 'temperature');
    expect(temp.length).toBe(1);
  });

  it('warns about excessive feed rate', () => {
    const lines = [
      'G28',
      'G1 X10 Y10 F20000', // very high feed rate
    ];
    const issues = detectGcodeErrors(lines);
    const feedrate = issues.filter(i => i.category === 'feedrate' && i.message.includes('high'));
    expect(feedrate.length).toBe(1);
  });

  it('errors on arc without radius or endpoint', () => {
    const lines = ['G2']; // arc with nothing
    const issues = detectGcodeErrors(lines);
    const arc = issues.filter(i => i.category === 'arc');
    expect(arc.length).toBe(1);
    expect(arc[0].severity).toBe('error');
  });

  it('errors on zero radius arc', () => {
    const lines = ['G2 X10 Y10 R0'];
    const issues = detectGcodeErrors(lines);
    const arc = issues.filter(i => i.category === 'arc' && i.message.includes('zero'));
    expect(arc.length).toBe(1);
    expect(arc[0].severity).toBe('error');
  });

  it('warns about duplicate words', () => {
    const lines = ['G1 X10 X20 Y10 F1500']; // duplicate X
    const issues = detectGcodeErrors(lines);
    const dup = issues.filter(i => i.category === 'duplicate-word');
    expect(dup.length).toBe(1);
  });

  it('returns no issues for clean G-code', () => {
    const lines = [
      'G28',
      'M104 S200',
      'M109 S200',
      'G1 X10 Y10 Z0.2 F1500',
      'G1 X100 Y10 E5 F1800',
    ];
    const issues = detectGcodeErrors(lines);
    expect(issues.length).toBe(0);
  });

  it('handles empty input', () => {
    expect(detectGcodeErrors([])).toEqual([]);
  });
});

// ── Work coordinate system tracking ──

describe('parseWorkCoordinateSystems', () => {
  it('parses G54-G59 commands', () => {
    const lines = ['G54', 'G1 X10', 'G55', 'G1 X20', 'G59'];
    const wcs = parseWorkCoordinateSystems(lines);
    expect(wcs.length).toBe(3);
    expect(wcs[0].code).toBe('G54');
    expect(wcs[0].wcsNumber).toBe(0);
    expect(wcs[1].code).toBe('G55');
    expect(wcs[1].wcsNumber).toBe(1);
    expect(wcs[2].code).toBe('G59');
    expect(wcs[2].wcsNumber).toBe(5);
  });

  it('parses inline offsets', () => {
    const lines = ['G54 X1 Y2 Z3'];
    const wcs = parseWorkCoordinateSystems(lines);
    expect(wcs.length).toBe(1);
    expect(wcs[0].offsets).not.toBeNull();
    expect(wcs[0].offsets!.x).toBe(1);
    expect(wcs[0].offsets!.y).toBe(2);
    expect(wcs[0].offsets!.z).toBe(3);
  });

  it('returns null offsets when no inline values', () => {
    const lines = ['G54'];
    const wcs = parseWorkCoordinateSystems(lines);
    expect(wcs[0].offsets).toBeNull();
  });

  it('returns empty for no WCS commands', () => {
    expect(parseWorkCoordinateSystems(['G1 X10 Y10'])).toEqual([]);
  });
});

describe('getActiveWCS', () => {
  it('returns the active WCS at a given line', () => {
    const lines = ['G54', 'G1 X10', 'G55', 'G1 X20'];
    const wcs = parseWorkCoordinateSystems(lines);
    expect(getActiveWCS(wcs, 0)?.code).toBe('G54');
    expect(getActiveWCS(wcs, 2)?.code).toBe('G55');
  });

  it('returns null for empty systems', () => {
    expect(getActiveWCS([], 10)).toBeNull();
  });
});

// ── Stock/bed dimensions parsing ──

describe('parseStockDimensions', () => {
  it('parses stock dimensions from comments', () => {
    const lines = [';STOCK_X: 100', ';STOCK_Y: 100', ';STOCK_Z: 50', 'G1 X10'];
    const stock = parseStockDimensions(lines);
    expect(stock).not.toBeNull();
    expect(stock!.max[0]).toBe(100);
    expect(stock!.max[1]).toBe(100);
    expect(stock!.max[2]).toBe(50);
  });

  it('parses bed dimensions from comments', () => {
    const lines = [';BED_X: 200', ';BED_Y: 200', 'G1 X10'];
    const stock = parseStockDimensions(lines);
    expect(stock).not.toBeNull();
    expect(stock!.max[0]).toBe(200);
    expect(stock!.max[1]).toBe(200);
  });

  it('parses print area bounds', () => {
    const lines = [';print_area_min_x: 0', ';print_area_max_x: 220', ';print_area_min_y: 0', ';print_area_max_y: 220'];
    const stock = parseStockDimensions(lines);
    expect(stock).not.toBeNull();
    expect(stock!.min[0]).toBe(0);
    expect(stock!.max[0]).toBe(220);
  });

  it('parses Cura MACHINE_BOUNDS', () => {
    const lines = [';MACHINE_BOUNDS 0,0,200,200'];
    const stock = parseStockDimensions(lines);
    expect(stock).not.toBeNull();
    expect(stock!.min[0]).toBe(0);
    expect(stock!.min[1]).toBe(0);
    expect(stock!.max[0]).toBe(200);
    expect(stock!.max[1]).toBe(200);
  });

  it('parses PrusaSlicer bed_shape', () => {
    const lines = ['; bed_shape = 0x0,200x0,200x200,0x200'];
    const stock = parseStockDimensions(lines);
    expect(stock).not.toBeNull();
    expect(stock!.bedShape).toBe('rectangular');
  });

  it('parses circular bed shape', () => {
    const lines = [';bed_shape: circle', ';BED_X: 200', ';BED_Y: 200'];
    const stock = parseStockDimensions(lines);
    expect(stock).not.toBeNull();
    expect(stock!.bedShape).toBe('circular');
  });

  it('returns null for no dimensions', () => {
    expect(parseStockDimensions(['G1 X10 Y10'])).toBeNull();
  });

  it('returns null for empty input', () => {
    expect(parseStockDimensions([])).toBeNull();
  });
});

// ── Print time estimation ──

describe('estimatePrintTime', () => {
  it('parses Cura TIME comment', () => {
    const lines = [';TIME:3600', 'G1 X10 Y10 F1500'];
    const est = estimatePrintTime(lines);
    expect(est.estimatedTime).toBe(3600);
    expect(est.method).toBe('comment');
    expect(est.confidence).toBeGreaterThan(0.9);
  });

  it('parses PrusaSlicer estimated printing time', () => {
    const lines = ['; estimated printing time = 1h 30m 0s'];
    const est = estimatePrintTime(lines);
    expect(est.estimatedTime).toBe(5400); // 1h30m = 5400s
    expect(est.method).toBe('comment');
  });

  it('estimates from feed rates when no comment', () => {
    const lines = [
      'G28',
      'G1 X0 Y0 Z0.2 F3600',  // 3600 mm/min = 60 mm/s
      'G1 X100 Y0 E5 F3600',   // 100mm at 60mm/s ≈ 1.67s
    ];
    const est = estimatePrintTime(lines);
    expect(est.estimatedTime).toBeGreaterThan(0);
    expect(est.method).toBe('feedrate');
    expect(est.moveCount).toBeGreaterThan(0);
  });

  it('returns zero for empty input', () => {
    const est = estimatePrintTime([]);
    expect(est.estimatedTime).toBe(0);
  });

  it('returns zero for comment-only input', () => {
    const est = estimatePrintTime(['; comment only']);
    expect(est.estimatedTime).toBe(0);
  });
});

// ── Selection-scoped metrics ──

describe('computeSelectionMetrics', () => {
  it('computes metrics for a range of lines', () => {
    const lines = [
      'G28',
      'G1 X0 Y0 Z0.2 F1500',
      'G1 X100 Y0 E5 F1800',
      'G1 X100 Y100 E10 F1800',
      'G1 X0 Y100 E15 F1800',
    ];
    const metrics = computeSelectionMetrics(lines, 1, 4);
    expect(metrics.startLine).toBe(1);
    expect(metrics.endLine).toBe(4);
    expect(metrics.moveCount).toBe(3);
    expect(metrics.pathLength).toBeCloseTo(300, 0); // 100+100+100
    expect(metrics.extrusionLength).toBeCloseTo(15, 0); // 5+5+5
    expect(metrics.estimatedTime).toBeGreaterThan(0);
    expect(metrics.feedRateRange.min).toBe(1500);
    expect(metrics.feedRateRange.max).toBe(1800);
  });

  it('handles single line selection', () => {
    const lines = ['G1 X10 Y10 F1500'];
    const metrics = computeSelectionMetrics(lines, 0, 0);
    expect(metrics.moveCount).toBe(0); // no previous position
  });

  it('handles empty range', () => {
    const lines = ['G1 X10 Y10 F1500'];
    const metrics = computeSelectionMetrics(lines, 5, 10);
    expect(metrics.moveCount).toBe(0);
  });

  it('handles comments-only lines in range', () => {
    const lines = ['; comment 1', '; comment 2', 'G1 X10 F1500'];
    const metrics = computeSelectionMetrics(lines, 0, 2);
    expect(metrics.moveCount).toBe(0); // comments skipped
  });

  it('handles empty input', () => {
    const metrics = computeSelectionMetrics([], 0, 10);
    expect(metrics.moveCount).toBe(0);
  });

  it('clamps selection to valid range', () => {
    const lines = ['G1 X10 F1500'];
    const metrics = computeSelectionMetrics(lines, -5, 100);
    expect(metrics.startLine).toBe(0);
    expect(metrics.endLine).toBe(0);
  });
});
