#!/usr/bin/env python3
"""
Generate a G-code file: an M×M square with N concentric perimeter walls.

Usage:
    python3 gen_square.py [--size M] [--walls N] [--spacing S] [--output FILE]

Defaults:
    M = 50        (square side length in mm)
    N = 5         (number of perimeter walls)
    S = 0.4       (spacing between walls in mm)
    output = square_MxM_Nwalls.gcode

The square is centered at the origin (0,0). The outermost wall is M×M,
each inner wall is inset by S mm on all sides.
"""

import argparse


def generate_square_gcode(size: float, walls: int, spacing: float, output: str) -> None:
    half = size / 2.0

    lines = []
    lines.append("; Generated by gen_square.py")
    lines.append(f"; Square: {size}mm × {size}mm, {walls} walls, {spacing}mm spacing")
    lines.append("; ---- Start ----")
    lines.append("G28 ; home all axes")
    lines.append("G90 ; absolute positioning")
    lines.append("M82 ; absolute extrusion")
    lines.append("G21 ; units = millimeters")
    lines.append("M104 S200 ; set hotend temperature")
    lines.append("M140 S60 ; set bed temperature")
    lines.append("M190 S60 ; wait for bed")
    lines.append("M109 S200 ; wait for hotend")
    lines.append("G1 Z5.0 F3000 ; lift nozzle")
    lines.append("G1 X0 Y0 F3000 ; move to origin")
    lines.append("G1 Z0.2 F3000 ; lower to first layer height")
    lines.append("")

    feed_rate = 1800  # mm/min

    for i in range(walls):
        inset = i * spacing
        x_min = -half + inset
        x_max = half - inset
        y_min = -half + inset
        y_max = half - inset

        # Skip if the square has degenerated
        if x_max <= x_min or y_max <= y_min:
            break

        lines.append(f"; --- Wall {i + 1}/{walls} ---")

        # Travel to start corner (bottom-left), no extrusion
        lines.append(f"G0 X{x_min:.3f} Y{y_min:.3f} F{feed_rate}")

        # Extrude around the square: bottom-left → bottom-right → top-right → top-left → bottom-left
        lines.append(f"G1 X{x_max:.3f} Y{y_min:.3f} E1.0 F{feed_rate}")
        lines.append(f"G1 X{x_max:.3f} Y{y_max:.3f} E2.0 F{feed_rate}")
        lines.append(f"G1 X{x_min:.3f} Y{y_max:.3f} E3.0 F{feed_rate}")
        lines.append(f"G1 X{x_min:.3f} Y{y_min:.3f} E4.0 F{feed_rate}")
        lines.append("")

    # End
    lines.append("; ---- End ----")
    lines.append("G1 Z5.0 F3000 ; lift nozzle")
    lines.append("M104 S0 ; turn off hotend")
    lines.append("M140 S0 ; turn off bed")
    lines.append("G28 X Y ; home XY")
    lines.append("M84 ; disable motors")

    with open(output, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {output}: {size}mm square, {walls} walls, {spacing}mm spacing")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a square G-code with N perimeter walls.")
    parser.add_argument("--size", "-s", type=float, default=50, help="Square side length in mm (default: 50)")
    parser.add_argument("--walls", "-n", type=int, default=5, help="Number of perimeter walls (default: 5)")
    parser.add_argument("--spacing", "-d", type=float, default=0.4, help="Spacing between walls in mm (default: 0.4)")
    parser.add_argument("--output", "-o", type=str, default="", help="Output file (default: square_<M>x<M>_<N>walls.gcode)")
    args = parser.parse_args()

    size_str = str(int(args.size)) if args.size == int(args.size) else str(args.size)
    output = args.output or f"square_{size_str}x{size_str}_{args.walls}walls.gcode"
    generate_square_gcode(args.size, args.walls, args.spacing, output)


if __name__ == "__main__":
    main()
