#!/usr/bin/env python3
"""
Generate a G-code file for a rounded square with N layers of shell
and straight grid infill.  The structure mimics real 3D-printer G-code
(rapid travel moves, extrusion at different feed rates, Z-hop
"perimeter puncture" patterns, multiple layers) but is compact enough
for unit testing.

Usage:
    python3 gen_rounded_square_gcode.py [--layers N] [--size S]
        [--shell-loops L] [--infill-spacing D] [--out FILE]

Defaults: 5 layers, 100 mm square, 2 shell loops, 5 mm infill spacing.
Output: stdout (or --out file).
"""

import argparse
import math
import sys


def rounded_square_points(size, corner_radius, segments_per_corner=8):
    """Return a list of (x, y) points tracing a rounded square CCW.

    The square is centered at (size/2, size/2).  Each corner is an arc
    with `segments_per_corner` segments.
    """
    r = corner_radius
    s = size
    cx = s / 2
    cy = s / 2
    # Corner centers
    centers = [
        (cx - s/2 + r, cy - s/2 + r),  # bottom-left
        (cx + s/2 - r, cy - s/2 + r),  # bottom-right
        (cx + s/2 - r, cy + s/2 - r),  # top-right
        (cx - s/2 + r, cy + s/2 - r),  # top-left
    ]
    # Arc start angles (CCW)
    angles = [180, 270, 0, 90]  # degrees

    pts = []
    for i, (arc_cx, arc_cy) in enumerate(centers):
        a0 = math.radians(angles[i])
        a1 = a0 + math.pi / 2  # 90-degree arc
        for j in range(segments_per_corner):
            t = j / segments_per_corner
            a = a0 + t * (a1 - a0)
            pts.append((arc_cx + r * math.cos(a),
                        arc_cy + r * math.sin(a)))
    # Close the loop (last point = first point)
    pts.append(pts[0])
    return pts


def generate_gcode(args):
    """Generate the G-code string."""
    lines = []
    W = lines.append

    # Header
    W("; Generated by gen_rounded_square_gcode.py")
    W("; Rounded square with shell + grid infill")
    W(f"; Layers: {args.layers}, Size: {args.size}mm, "
      f"Shell loops: {args.shell_loops}, Infill spacing: {args.infill_spacing}mm")
    W("G21 ; set units to mm")
    W("G90 ; absolute XYZ positioning")
    W("G92 E0 ; reset extrusion distance")
    W("G28 ; home all axes")
    W("")

    # Feed rates (in mm/min, as in real G-code)
    F_TRAVEL = 18000      # rapid travel
    F_PERIMETER = 14400   # shell/perimeter extrusion
    F_INFILL = 2400       # infill extrusion (slower)
    F_ZMOVE = 1200        # Z layer change
    F_PUNCTURE = 240      # Z-hop perimeter puncture

    layer_height = 0.3
    corner_radius = min(10.0, args.size * 0.1)
    shell_inset = 2.0     # mm between shell loops

    for layer in range(args.layers):
        z = layer_height * (layer + 1)
        W(f"; Layer {layer}")
        W(f"; Z = {z:.6f}")
        W(f";LAYER_CHANGE")
        W(f";Z:{z:.6f}")
        W(f";HEIGHT:{layer_height:.6f}")

        # Z move to layer height
        W(f"G0 Z{z:.6f} F{F_ZMOVE}")

        # --- Shell loops ---
        for loop in range(args.shell_loops):
            r = corner_radius - loop * shell_inset * 0.5
            if r < 1.0:
                r = 1.0
            s = args.size - loop * shell_inset * 2
            if s < 10.0:
                s = 10.0

            pts = rounded_square_points(s, r)

            # Travel to start
            x0, y0 = pts[0]
            W(f"G0 X{x0:.6f} Y{y0:.6f} F{F_TRAVEL}")

            # Z-hop "perimeter puncture" pattern (like punctperi2)
            W(f"G1 Z{z - 0.4:.6f} F{F_PUNCTURE} ; perimeter puncture")
            W(f"G1 Z{z:.6f} F{F_PUNCTURE}")

            # Extrude around the shell
            for i in range(1, len(pts)):
                x, y = pts[i]
                e = 0.05 * math.hypot(x - pts[i-1][0], y - pts[i-1][1])
                W(f"G1 X{x:.6f} Y{y:.6f} E{e:.6f} F{F_PERIMETER}")

                # Insert a perimeter puncture every few segments
                if i % 8 == 0 and i < len(pts) - 1:
                    W(f"G1 Z{z - 0.4:.6f} F{F_PUNCTURE} ; perimeter puncture")
                    W(f"G1 Z{z:.6f} F{F_PUNCTURE}")

        # --- Grid infill ---
        # Straight parallel lines in X direction
        infill_extent = args.size - 2 * corner_radius
        x_start = corner_radius
        x_end = args.size - corner_radius
        y_start = corner_radius
        y_end = args.size - corner_radius

        y = y_start
        line_idx = 0
        while y <= y_end + 0.01:
            # Travel to start of infill line
            if line_idx % 2 == 0:
                W(f"G0 X{x_start:.6f} Y{y:.6f} F{F_TRAVEL}")
                e = 0.05 * (x_end - x_start)
                W(f"G1 X{x_end:.6f} Y{y:.6f} E{e:.6f} F{F_INFILL}")
            else:
                W(f"G0 X{x_end:.6f} Y{y:.6f} F{F_TRAVEL}")
                e = 0.05 * (x_end - x_start)
                W(f"G1 X{x_start:.6f} Y{y:.6f} E{e:.6f} F{F_INFILL}")

            y += args.infill_spacing
            line_idx += 1

        # Straight parallel lines in Y direction (cross-fill)
        x = x_start
        line_idx = 0
        while x <= x_end + 0.01:
            if line_idx % 2 == 0:
                W(f"G0 X{x:.6f} Y{y_start:.6f} F{F_TRAVEL}")
                e = 0.05 * (y_end - y_start)
                W(f"G1 X{x:.6f} Y{y_end:.6f} E{e:.6f} F{F_INFILL}")
            else:
                W(f"G0 X{x:.6f} Y{y_end:.6f} F{F_TRAVEL}")
                e = 0.05 * (y_end - y_start)
                W(f"G1 X{x:.6f} Y{y_start:.6f} E{e:.6f} F{F_INFILL}")

            x += args.infill_spacing
            line_idx += 1

        W("")  # blank line between layers

    # Footer
    W("; End of G-code")
    W("M84 ; disable motors")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate rounded square G-code with shell + grid infill")
    parser.add_argument("--layers", type=int, default=5,
                        help="Number of layers (default: 5)")
    parser.add_argument("--size", type=float, default=100.0,
                        help="Square size in mm (default: 100)")
    parser.add_argument("--shell-loops", type=int, default=2,
                        help="Number of shell/perimeter loops (default: 2)")
    parser.add_argument("--infill-spacing", type=float, default=5.0,
                        help="Infill line spacing in mm (default: 5)")
    parser.add_argument("--out", type=str, default=None,
                        help="Output file (default: stdout)")
    args = parser.parse_args()

    gcode = generate_gcode(args)
    if args.out:
        with open(args.out, "w") as f:
            f.write(gcode)
        print(f"Wrote {len(gcode)} bytes to {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(gcode)


if __name__ == "__main__":
    main()
